# SPDX-FileCopyrightText: 2026 Axle Duggan (axlecoffee) <contact@axle.coffee>
# SPDX-License-Identifier: AGPL-3.0-only
services:
  haste:
    container_name: hst-axlecoffee
    build: .
    restart: unless-stopped
    ports:
      - "0.0.0.0:8292:8292"
    env_file: .env
    read_only: true
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    stop_grace_period: 30s

