# SPDX-FileCopyrightText: 2026 Axle Duggan (axlecoffee) <contact@axle.coffee>
# SPDX-License-Identifier: AGPL-3.0-only
name: Container build (no publishing)

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  build:
    name: Build Rust and WASM image locally
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v6
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3.11.1
      - name: Build Haste Server Docker image
        uses: docker/build-push-action@v6.18.0
        with:
          push: false
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: hst-axle-coffee:ci
